### ISSUE TITLE
Redirect Academics shortcut and People Finder toggle

### ISSUE THREAD

**Issue by bdleblanc** [DeckardLain/ON-Mod-Suite#16]
I apologize for leaving another issue when I could have mentioned this last week and just forgot to do so... :)

The new Academics view has a different URL that needs to be reflected in line 720. Currently it's `strLinkPrefix = schoolURL+"app/academics#academicprofile/";` and the new URL needs to be `strLinkPrefix = schoolURL+"sis-scheduling/user-profile/";`. (I would also prefer that the suffix go to /schedule rather than /attendance, but that's probably just me. It's just one more mouse click either way.)

You may need to also double check the code that displays the "Open in:" shortcuts so that it displays in the new Academics view as well.

One other very minor thing: would it be possible to add a toggle to the options to turn on and off the "press the number of the person you're looking up in People Finder to open their profile" feature? That feature overwrites the ability to search by a student's ID number, which I don't use often but sometimes need to and it can be a bit of a hassle to work my way around the feature.

Thanks Scott!!!

**Comment by DeckardLain** [comment]
I've been meaning to address these issues for a while, actually (especially People Finder).  Thanks for the nudge!

The link for switching user profiles to Academics has been updated to the new Academics profile, and the new Academics profile page is now properly detected so the other links get added under the name.  I'll eventually add a group of settings so that users can choose the specific area of the profile these links should go to by default.

The fact that I couldn't type User IDs into People Finder because of this mod feature actually bothered me too.  The idea I implemented was for the mod to only use numbers as a quick select if non-numeric text was already typed into the search box.  That way, you can still type an ID number when necessary but also have the quick select option when typing a name.  The only thing that wouldn't be handled is email addresses with numbers in them.  Hopefully, that's rare enough to not be an issue.  If I'm searching by email address, I typically copy/paste that anyway.

If you still think it would be useful to have the option to disable the mod feature in Settings, let me know.

**Comment by bdleblanc** [comment]
Nope, your solution to the user ID issue is perfect. Thanks again!! You are a wonderful resource, if no one's told you that lately. :)
